# Site settings
title: Pranav Maneriker
email: pranav[dot]maneriker[at]dolby.com
email2: pranavmane@gmail[dot]com
description: 
#baseurl: "http://home.iitk.ac.in/~mpranav" # the subpath of your site, e.g. /blog/
baseurl: "" #config for local testing
url: "" # the base hostname & protocol for your site
github_username:  pranavmaneriker
orcid: 0000-0003-1333-4424
scholar_id:  9t8gbkkAAAAJ
linkedin_id: pranav-maneriker
footertitle: Contact
future: true
collections:
  publications:
    output: true

# Build settings
markdown: kramdown

