# Site settings
title: Pranav Maneriker
email: maneriker.1@osu.edu
email2: pranavmane@gmail.com
description: 
#baseurl: "http://home.iitk.ac.in/~mpranav" # the subpath of your site, e.g. /blog/
baseurl: "" #config for local testing
url: "" # the base hostname & protocol for your site
twitter_username: PM_1729
github_username:  pranavmaneriker
gitlab_username:  pranavmane
footertitle: Contact
future: true
collections:
  publications:
    output: true

# Build settings
markdown: kramdown

